### ISSUE TITLE
Solaris: test-minconf.cpp:95:69: error: ‘Approx’ was not declared in this scope

### ISSUE THREAD

**Issue by bitbacchus** [r-spatialecology/spectre#101]
On Solaris
```
test-minconf.cpp: In function ‘void testthat_disabled_test_60()’:
test-minconf.cpp:95:69: error: ‘Approx’ was not declared in this scope
     expect_true(mc.test_calc_error(commonness, target) == Approx(0.0));
                                                                     ^
/home/ripley/R/Lib32/testthat/include/testthat/testthat.h:184:49: note: in definition of macro ‘expect_true’
 # define expect_true(__X__)             (void) (__X__)
                                                 ^
*** Error code 1
make: Fatal error: Command failed for target `test-minconf.o'
```

**Comment by bitbacchus** [comment]
This is an upstream issue. Testthat does not support C++ unit tests on Solaris (https://github.com/r-lib/testthat/issues/1257) and automatically skips them with testthat (>= 3.0.2).

But I think we have to avoid compiling the tests as well. My idea is to simply tell the compiler to skip our test with a compiler macro (8633fd1) but it kinda feels like a hack. It also might not work with every compiler... 

The code is here:
https://github.com/r-spatialecology/spectre/tree/Fix%23101

can we test it on their Solaris machine before submitting it?

**Comment by mhesselbarth** [comment]
Maybe it's easier and cleaner to just add `skip_on_os("solaris")` to the testthat files in which we run rcpp tests?

We could try to use the `rhub` package to test on Solaris.

**Comment by bitbacchus** [comment]
> Maybe it's easier and cleaner to just add skip_on_os("solaris") to the testthat files in which we run rcpp tests?

Skipping the **run** of testthat on Solaris is handled by testthat itself, no problem there. As I understand it, the problem occurs on compiling the C++ tests.

**Comment by mhesselbarth** [comment]
Oh okay...I thought testthat just calls the C++ tests?

**Comment by bitbacchus** [comment]
yes, but it needs some C++ code for that. In particular, the Approx() function is provided by testthat...

**Comment by mhesselbarth** [comment]
Okay I think I am not really getting what the problem is then? If we would just add the `skip_on_os("solaris")` all  C++ that causes the issues wouldn't be called on Solaris while testing and thus not causing any issues? Or am I being stupid here :D

**Comment by bitbacchus** [comment]
> If we would just add the skip_on_os("solaris") all C++ that causes the issues wouldn't be called on Solaris while testing and thus not causing any issues?

If I interpret the issue correctly, the problem does not occur when thestthat is called but when spectre is built, because we use in our C++ unit tests some C++ "library" code provided by testthat. This code is needed to link testthat to the C++ test framework (Catch2).

**Comment by bitbacchus** [comment]
But PR #102  seems to work...

**Comment by mhesselbarth** [comment]
Okay...well if it works it works :)
