### ISSUE TITLE
delete vignettes/getting_started_with_spectre.R?

### ISSUE THREAD

**Issue by mspngnbrg** [r-spatialecology/spectre#106]
the file seems obsolete since we have the "minimal example" now

**Comment by csim063** [comment]
The `getting_started_with_spectre` vignette is a more fleshed out/prosaic version of `minimal_example` so not sure it should be deleted.

**Comment by mspngnbrg** [comment]
I saw it and like it, we should geeting_started_with_spectre.R IMO
