### ISSUE TITLE
fixed seed somewhere?

### ISSUE THREAD

**Issue by mspngnbrg** [r-spatialecology/spectre#109]
It looks like a fixed seed is set somewhere, since I always get the same results in an analysis running spectre installed/built from "main" branch.

**Comment by mspngnbrg** [comment]
if (is.na(seed)) {
    seed <- Sys.getpid() # sample(0:.Machine$integer.max, 1)
  } 
@bitbacchus : this caused the seed error

**Comment by bitbacchus** [comment]
@mhesselbarth this was your commit here: https://github.com/r-spatialecology/spectre/commit/d92b69fd5877190cae0a5952dacb7fc7e9d379d1

What was your idea? Should we just un-do it (i.e. use `sample(0:.Machine$integer.max, 1)` )?

**Comment by mhesselbarth** [comment]
Mmh...`sample(0:.Machine$integer.max, 1)` threw an error somewhere during the `devtools::check_win_release()`. There is no issue about this, but an e-mail thread (see quote here). Strange that the System Process ID is not unique though and this leads to issue?

> Hey, 
> 
> Yes the note shouldn’t matter once we set the repo to public. 
> 
> If I get the error message correctly, there is a problem with the seed generation if no user seed is provided. I just pushed a change to the main branch that uses the System Process ID as seed if none is specified. This might be a bit more stable than sampling from 0 to the maximum integer number. Can you please re-submit the check from the main branch and see if that helped. 
> 
> Cheers,
> Max
>

**Comment by mspngnbrg** [comment]
@mhesselbarth "Strange that the System Process ID is not unique though and this leads to issue?" This is an issue with replicates, since all replicates use the same process ID of the R session then.

**Comment by bitbacchus** [comment]
It's more a convenience issue, I think. The most appropriate way is to manually provide seeds for each run to have everything reproducible. But for testing or so it would be nice to generate some random seed.

**Comment by bitbacchus** [comment]
Maybe the simplest hack would be:
```R
  if (is.na(seed)) {
    seed <- sample(0:2147483647, 1) # .Machine$integer.max <- solves some issue on Windows machines
  }
```

What do you think?

**Comment by mhesselbarth** [comment]
I think that should work. An alternative would be to use the current time `seed <- as.numeric(gsub("[: -]", "" , format(Sys.time(), "%X")))` but either is fine I think. 

I get why the `Sys.pid` was a stupid idea. Obviously it's only different across different R session...stupid me.

**Comment by bitbacchus** [comment]
> I think that should work. An alternative would be to use the current time `seed <- as.numeric(gsub(":", "" , format(Sys.time(), "%X")))` but either is fine I think.

Sys.time has a seconds-resolution (afaik) which might be too long (e.g. for benchmarks)

**Comment by mhesselbarth** [comment]
> Sys.time has a seconds-resolution (afaik) which might be too long (e.g. for benchmarks)

Make sense. Yeah, I don't see any problems with the sampling approach...

**Comment by bitbacchus** [comment]
Should be fixed.
