### ISSUE TITLE
Remove explicit call to gdm

### ISSUE THREAD

**Issue by csim063** [r-spatialecology/spectre#111]

**Comment by mspngnbrg** [comment]
I changed both vignettes (minimal example & getting_started_with...), added a new .rds to data containing a random species list, its Bray-Curtis dissimilarity and alpha diversity. The new .rds is produced here: generate_minimal_example_data.R. Are there more places where we have to get rid of the gdm package, maybe also in "suggests"?

**Comment by mhesselbarth** [comment]
Not sure where you save the `rds` object? And we also can't put the `generate_minimal_example_data.R` in the `R` folder. Or at least we shouldn't even if we can and this doesn't trigger a warning. 

I would suggest to just ship the object as "internal" data of the package and put the script into `data-raw`. I can take care of this a bit later today.

**Comment by mspngnbrg** [comment]
Thanks for giving directions, Max! I followed the instructions here and I hope it works now. https://r-pkgs.org/data.html

**Comment by mhesselbarth** [comment]
Well done. That looks much better and cleaner! I only change one small bit and set the `internal = FALSE` in the `use_data()` function. This just makes the data a little bit easier to access and I don't think we need to make it not accessible by the users. 

Related to this, where are `alpha_list`, `estimated_gamma`, and `target_matrix` (data objects) coming from. Do we want a script in `data-raw/` to be able to reproduce them as well?

**Comment by mspngnbrg** [comment]
At the moment, we have NO script in data-raw/ that is able to reproduce the simulated data for a) the minimum_example and b) the test-generate_commonness_matrix_from_gdm.R script.  This is mainly because I had the impression, but am not 100% sure, that calling the gdm-package from data-raw/ caused some automated tests to fail. Anyway, the simulated data is available from within the package now.

**Comment by mhesselbarth** [comment]
If `gdm` is used only within `data-raw/` this should not cause any problems since these scripts are actually never run during any testing, installation, etc...
