### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by mhesselbarth** [r-spatialecology/spectre#116]
How is the webpage currently build? Do we want to render the vignettes and README as homepage? I am sure we can also link to the benchmark results there.

**Comment by bitbacchus** [comment]
Only the `/dev/` part (i.e. the two links) is built automatically, the actual `index.html` is handcrafted ;-) 
Yes, we want the README and for sure the vignettes as homepage. Do you have a recipe for this and could do that?

**Comment by mhesselbarth** [comment]
Yes, I can take care of that!

**Comment by mhesselbarth** [comment]
Alright, I updated the homepage (same link) and added everything to automatically deploy it on the main branch (using a new github action). 

You can use the `_pkgdown.yml` file to include new subpages to the homepage. Currently, I don't use any menus because we don't have too many pages, but if we want to include more we can use dropdown menus as well.

@bitbacchus I deactivated the doxygen github action manually for now because it also deploys to a gh-pages branch which is a problem. Could you rewrite the last job of the action that the results are simply written into a new vignette? We could then use this to simply link to it on the homepage.

**Comment by bitbacchus** [comment]
What happens when the Doxygen action deploys to the gh-pages branch? It deploys to a different folder, should be no problem, or does the action clear the whole branch? The benchmark action also tries to deploy to the gh-pages branch. 

When I write it to a vignette, doesn't it become part of the package then?

**Comment by mhesselbarth** [comment]
The `pkgdown` action didn't work and returned an error message along of the lines of "gh-pages branch not empty and not created by pkgdown". So it seems like we cannot have them all deploy to the branch. I mean, also makes sense to me in a way. 

Wait, I think I kind of confused the Doxygen and benchmark action or rather thought they are the same. Whats the Doxygen again exactly? 

I just created an `vignettes/articles/` folder. Those files would be accessible for the homepage (so we can just create a subpage with the latest benchmark and Doxygen results), but are not build as vignettes. I added a currently empty Rmarkdown file there to test this. 

Maybe that's a solution to write the results of both actions into a Markdown file in that folder?

**Comment by bitbacchus** [comment]
> Wait, I think I kind of confused the Doxygen and benchmark action or rather thought they are the same. Whats the Doxygen again exactly?

Both actions, Doxygen and Benchmark, create their own websites with subfolders, JS and everything. Doxygen is where Roxygen got the idea from, i.e. it generates documentation from our C++ code. I think this does not work from a vignettes/articles folder, or am I mistaken?

**Comment by mhesselbarth** [comment]
Oh okay....I had no idea what Doxygen is tbh. 

Wait, why don't we not just use Roxygen to also document the C++ function the same as the R functions? Do we even need an GH action for this?

**Comment by bitbacchus** [comment]
> Wait, why don't we not just use Roxygen to also document the C++ function the same as the R functions? Do we even need an GH action for this?

I believe Roxygen can only interpret comments in R code. Otherwise, that would be the best solution for sure.

**Comment by mhesselbarth** [comment]
We can definitely just Roxygen as well, see https://gallery.rcpp.org/articles/documenting-rcpp-packages/. This gets automatically translated.

```
#include <Rcpp.h>

//' Multiplies two doubles
//'
//' @param v1 First value
//' @param v2 Second value
//' @return Product of v1 and v2
// [[Rcpp::export]]
double mult( double v1, double v2 ) {return v1*v2;}
```

**Comment by bitbacchus** [comment]
Oh, cool! I'll take care of this. Now we only need to figure out how we deal with the benchmark action.
